feat: init project

diff --git a/.gitea/workflows/main-maven-jar.yml b/.gitea/workflows/main-maven-jar.yml
--- a/.gitea/workflows/main-maven-jar.yml
+++ b/.gitea/workflows/main-maven-jar.yml
@@ -12,6 +12,17 @@ jobs:
     # 指定了作业运行的环境
     runs-on: windows
     steps:
+      - name: Debug Secret
+        run: |
+          if [ -z "${{ secrets.ACTION_TOKEN }}" ]; then
+            echo "ERROR: ACTION_TOKEN is empty or not found!"
+            exit 1
+          else
+            echo "ACTION_TOKEN is set (length: ${#TOKEN})"
+          fi
+        shell: bash
+        env:
+          TOKEN: ${{ secrets.ACTION_TOKEN }}
       - name: Checkout repository
         uses: https://gitea.com/actions/checkout@v6
         with:
